[project]
name = "yolov7"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ruben Arts <ruben.arts@hotmail.com>"]
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[commands]
start = "python detect.py --source 0"


[dependencies]
matplotlib = ">=3.2.2"
numpy = ">=1.18.5,<1.24"
opencv = ">=4.1.1"
pillow = ">=7.1.2"
pyyaml = ">=5.3.1"
requests = ">=2.23.0"
scipy = ">=1.4.1"
pytorch = ">=1.7.0,!=1.12.0"
torchvision = ">=0.8.1,!=0.13.0"
tqdm = ">=4.41.0"
protobuf = "<4.21.3"
brotlicffi = "*"
typing_extensions = "*"

tensorboard = ">=2.4.1"

pandas = ">=1.1.4"
seaborn = ">=0.11.0"

ipython = "*"
psutil = "*"
#thop = "*"
pip = "*"

# [target.linux-64.dependencies]
# pytorch-gpu = ">=1.7.0,!=1.12.0"
